### ISSUE TITLE
Question: License?

### ISSUE THREAD

**Issue by Timtendo12** [boehs/boehs.github.io#29]
Hi! Amazing project.

What is the license for this project? I'm considering taking inspiration from your site design if that's okay with you.

**Comment by boehs** [comment]
That's wonderful! Would GPLv3 work for you?

**Comment by boehs** [comment]
In [0ee6110](https://github.com/boehs/site/commit/0ee61109d89013e81ccac7c1fff5c4618aa0ffd2), The AGPLv3 was adopted. If that is an issue do let me know.
